version: '3'
services:
    postgres:
        image: 'postgres:15.2'
        ports:
            - '5432:5432'
        environment:
            POSTGRES_DB: 'trabalhoJAVA'
            POSTGRES_USER: 'user'
            POSTGRES_PASSWORD: 'password'
            POSTGRES_HOST_AUTH_METHOD : 'trust'
    adminer:
        image: 'adminer:latest'
        ports:
            - 8080:8080
        depends_on:
            - postgres